In [47]:
import numpy as np

In [68]:
list1 = np.arange(1,11)

In [69]:
list1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
N = 5

# Vander package in python

In [130]:

np.vander(mat1, N, increasing=True)

array([[    1,     1,     1,     1,     1],
       [    1,     2,     4,     8,    16],
       [    1,     3,     9,    27,    81],
       [    1,     4,    16,    64,   256],
       [    1,     5,    25,   125,   625],
       [    1,     6,    36,   216,  1296],
       [    1,     7,    49,   343,  2401],
       [    1,     8,    64,   512,  4096],
       [    1,     9,    81,   729,  6561],
       [    1,    10,   100,  1000, 10000]])

# Vander matrix function written in python

In [131]:
def vander_matrix(element,N):
    out  = [] 
    for i in range(len(element)):
        list3 = []
        for j in range(0,N):
            list3.append(np.power(element[i],j))
    
        out.append(list3)
    return np.array(out)

In [132]:
matt_out2 =  vander_matrix(list1,5)

In [134]:
print(matt_out2)

[[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     3     9    27    81]
 [    1     4    16    64   256]
 [    1     5    25   125   625]
 [    1     6    36   216  1296]
 [    1     7    49   343  2401]
 [    1     8    64   512  4096]
 [    1     9    81   729  6561]
 [    1    10   100  1000 10000]]
